### ISSUE TITLE
Update Dockerfiles to use the new name for MMS

### ISSUE THREAD

**Issue by dotgc** [aws/sagemaker-mxnet-inference-toolkit#119]
MMS changed the pip name to multi-model-server from mxnet-model-server

The pip dependency here should be fixed accordingly:
* [CPU Dockerfile](https://github.com/aws/sagemaker-mxnet-serving-container/blob/master/docker/1.6.0/py3/Dockerfile.cpu#L74)
* [GPU Dockerfile](https://github.com/aws/sagemaker-mxnet-serving-container/blob/master/docker/1.6.0/py3/Dockerfile.gpu#L71)

New PyPi link: https://pypi.org/project/multi-model-server/
Old link: https://pypi.org/project/mxnet-model-server/

**Comment by ChuyangDeng** [comment]
Does this apply to GPU dockerfiles as well?

**Comment by dotgc** [comment]
I should have been clearer in the issue description. Basically we wanted to use multi-model-server in the container. Release 1.0.9 onwards, MMS supports a `preload_model` option that we want to make use of, which is currently not possible with the current container.

**Comment by laurenyu** [comment]
the Dockerfiles have been moved to https://github.com/aws/deep-learning-containers - I believe upgrading to the new MMS is in progress

**Comment by laurenyu** [comment]
this has now been done:
* [Python 3 + CPU](https://github.com/aws/deep-learning-containers/blob/master/mxnet/inference/docker/1.6.0/py3/Dockerfile.cpu#L101)
* [Python 3 + GPU](https://github.com/aws/deep-learning-containers/blob/master/mxnet/inference/docker/1.6.0/py3/Dockerfile.gpu#L98)
* [Python 2 + CPU](https://github.com/aws/deep-learning-containers/blob/master/mxnet/inference/docker/1.6.0/py2/Dockerfile.cpu#L84)
* [Python 2 + GPU](https://github.com/aws/deep-learning-containers/blob/master/mxnet/inference/docker/1.6.0/py2/Dockerfile.gpu#L81)
