### ISSUE TITLE
Container Support for Gluon Toolkits

### ISSUE THREAD

**Issue by szha** [aws/sagemaker-mxnet-inference-toolkit#71]
Reference: 0413477381

The Gluon toolkits (GluonCV, GluonNLP, GluonTS) are the essential constituents of the MXNet ecosystem. Being a container for MXNet, and given that even packages outside of the ecosystem such as scikit-learn and pandas are included, shall we make sure we add these toolkits in the next release?

Related: https://github.com/aws/sagemaker-mxnet-container/issues/111

**Comment by velociraptor111** [comment]
This is so true!

**Comment by laurenyu** [comment]
the Dockerfiles are now housed in https://github.com/aws/deep-learning-containers - please open an issue in that repository
